### ISSUE TITLE
search on console crashes the script

### ISSUE THREAD

**Issue by tilles80** [RxLaboratory/Duik#1000]
> Before submitting a bug report, please follow these steps which will help us diagnose your problem:

- [ ] Download "DuSI": https://rxlaboratory.org/tools/dusi/
    A script to try to fix issues and get needed system information for debugging
- [ ] Run DuSI in After Effects and click the "Fix / Uninstall" button.
- [ ] Try again to run Duik and try to reproduce the bug. If it's fixed, congrats! If not, continue to the next step.
- [ ] Run DuSI again and click the "Get System Information" button. It will ask you to save the info to a file. Choose one, and post it here!
- [ ] Write your bug report below, and don't forget to attach the file saved by DuSI or copy/paste its content here. (it's a simple text file)

----

**Description**

Script gets unresponsive after searching in the console for "wiggle" and hitting "enter".
I have to restart the script, to show the actual error, then restart again to go back to normal.

**To Reproduce**

1. go to the console tab
2. type "wiggle"
3. hit <enter> on the keyboard

**Error description, if any**

File: 
Line number: 2911
Error message: Expected ) - undefined is not an object (see attached file)

**Additional context**

**System information**

Generated by DuSI v1.4.0

[OS]
OS:Windows/64 10.0  
Filesystem:Windows

[Host]
Host:aftereffects
HostVersion:23.0x59

[Folders]
appData:C:\ProgramData # [R,W]
appPackage:C:\Program Files\Adobe\Adobe After Effects 2023\Support Files # [R,-]
commonFiles:C:\Program Files\Common Files # [R,-]
![Captura de tela 2023-02-01 102022](https://user-images.githubusercontent.com/29214751/216058848-905423c7-80e5-4f90-94ba-999804374f86.jpg)

current:C:\Program Files\Adobe\Adobe After Effects 2023\Support Files # [R,-]
desktop:C:\Users\Mymax\Desktop # [R,W]
myDocuments:C:\Users\Mymax\Documents # [R,W]
startup:C:\Program Files\Adobe\Adobe After Effects 2023\Support Files # [R,-]
system:C:\WINDOWS\SYSTEM32 # [R,-]
temp:C:\Users\Mymax\AppData\Local\Temp # [R,W]
userData:C:\Users\Mymax\AppData\Roaming # [R,W]

**Comment by Nico-Duduf** [comment]
fixed in 17.0.2
