### ISSUE TITLE
The opacity settings are not modified from the bone settings

### ISSUE THREAD

**Issue by urekmazino00** [RxLaboratory/Duik#1001]
When using the bone settings, the opacity settings are only modified when the size is changed

https://user-images.githubusercontent.com/48952173/216089441-9ab35d69-372b-488e-8b66-9498bcf4656d.mp4

**Comment by Nico-Duduf** [comment]
Fixed in the upcoming 17.0.2

**Comment by urekmazino00** [comment]
thanks :)
