### ISSUE TITLE
Impossible d'exécuter le script à la ligne 105. PREFType n'est pas définie.

### ISSUE THREAD

**Issue by Carou02** [RxLaboratory/Duik#1006]
> Before submitting a bug report, please follow these steps which will help us diagnose your problem:

- [x] Download "DuSI": https://rxlaboratory.org/tools/dusi/
    A script to try to fix issues and get needed system information for debugging
- [x] Run DuSI in After Effects and click the "Fix / Uninstall" button.
- [x] Try again to run Duik and try to reproduce the bug. If it's fixed, congrats! If not, continue to the next step.
- [x] Run DuSI again and click the "Get System Information" button. It will ask you to save the info to a file. Choose one, and post it here!
- [x] Write your bug report below, and don't forget to attach the file saved by DuSI or copy/paste its content here. (it's a simple text file)

----

**Description**

Each time I try to launch the "Duik Angela.jsx" script from AE CS6, I get the same error message. 
"Impossible d'exécuter le script à la ligne 105. PREFType n'est pas définie."

**To Reproduce**

1. Fichier ­> Scritp > Exécuter Script > 
2. C:\Program Files\Adobe\Adobe After Effects CS6\Support Files\Scripts\ScriptUI Panels
3. Exécute "Duik Angela.jsx"
4. Message d'erreur : Impossible d'exécuter le script à la ligne 105. PREFType n'est pas définie.

**Error description, if any**

File: Duik Angela.jsx
Line number: 105
Error message: 

**Additional context**

Étrangement, mon OS indique que je roule sur window 7 et pourtant je suis sur Window 10 selon mon système. 

**System information**

Generated by DuSI v1.4.0

[OS]
OS:Windows 7/64 6.2  
Filesystem:Windows

[Host]
Host:aftereffects
HostVersion:11.0.4x2

[Folders]
appData:C:\ProgramData # [R,W]
appPackage:C:\Program Files\Adobe\Adobe After Effects CS6\Support Files # [R,-]
commonFiles:C:\Program Files\Common Files # [R,-]
current:C:\Program Files\Adobe\Adobe After Effects CS6\Support Files # [R,-]
desktop:D:\Users\AC\Desktop # [R,W]
myDocuments:C:\Users\AC\Documents # [R,W]
startup:C:\Program Files\Adobe\Adobe After Effects CS6\Support Files # [R,-]
system:C:\WINDOWS\SYSTEM32 # [R,-]
temp:C:\Users\AC~1\AppData\Local\Temp # [R,W]
userData:C:\Users\AC\AppData\Roaming # [R,W]

Merci pour votre aide.

**Comment by Nico-Duduf** [comment]
Duik Ángela n'est pas compatible CS6
