### ISSUE TITLE
Freeze when Extract Controllers

### ISSUE THREAD

**Issue by TiegoCampos** [RxLaboratory/Duik#1007]
> Before submitting a bug report, please follow these steps which will help us diagnose your problem:

- [x] Download "DuSI": https://rxlaboratory.org/tools/dusi/
    A script to try to fix issues and get needed system information for debugging
- [x] Run DuSI in After Effects and click the "Fix / Uninstall" button.
- [x] Try again to run Duik and try to reproduce the bug. If it's fixed, congrats! If not, continue to the next step.
- [x] Run DuSI again and click the "Get System Information" button. It will ask you to save the info to a file. Choose one, and post it here!
- [x] Write your bug report below, and don't forget to attach the file saved by DuSI or copy/paste its content here. (it's a simple text file)

----

**Description**

When I try Extract Controllers, the loading windows appears, saying it working, but load stay forever; the process isn't complete. I close the window, and when I close After Effects, even without saving (which AE generally asks to save project), the project is automatically saved. I reopen the project and the parent composition has been duplicated on project panel. It's just bizarre.

**To Reproduce**

1. Create the bone structures, associate them to the parts o illustration, auto-rig them.
2. Put the comp of 1 into a parent comp.
3. Select the comp child and hit Extract Controllers.

**Error description, if any**

None.

**Additional context**

When try to extract controllers from a completed rig, and when try to extract controllers from parts (e.g. only an arm)

**System information**

Generated by DuSI v1.4.0

[OS]
OS:Windows/64 10.0  
Filesystem:Windows

[Host]
Host:aftereffects
HostVersion:23.1x83

[Folders]
appData:C:\ProgramData # [R,W]
appPackage:C:\Program Files\Adobe\Adobe After Effects 2023\Support Files # [R,-]
commonFiles:C:\Program Files\Common Files # [R,-]
current:C:\Users\Tiego\Desktop\OneDrive_1_03-02-2023 # [R,W]
desktop:C:\Users\Tiego\Desktop # [R,W]
myDocuments:C:\Users\Tiego\Documents # [R,W]
startup:C:\Program Files\Adobe\Adobe After Effects 2023\Support Files # [R,-]
system:C:\Windows\SYSTEM32 # [R,-]
temp:C:\Users\Tiego\AppData\Local\Temp # [R,W]
userData:C:\Users\Tiego\AppData\Roaming # [R,W]

**Comment by TiegoCampos** [comment]
Updating from duik 17.0.0 to duik 17.0.1, now the same task runs to me this error:
![image](https://user-images.githubusercontent.com/29361763/216900364-c272bcc7-9e37-4c4f-abf7-8487738d0c7d.png)

**Comment by Nico-Duduf** [comment]
This should be fixed in 17.0.2
