### ISSUE TITLE
Duik Bassel/Angela Rig with Puppet pin

### ISSUE THREAD

**Issue by Mitsukatsu** [RxLaboratory/Duik#1046]
Hi there,
i tried to make a leg-rig in Duik Bassel and Duik Angela and keep running into this problem:
I have a leg made of seperate layers (thigh, calf, foot) and added puppet pins on the foot layer for the foot roll and ability to move the toes.
i rig everything and when i want to rotate or move the foot there is a strange outline artefact showing up around the foot. or really weird distortions... only happens when i use the puppet tooll on it.
is it a bug or is something not parented correctly? actually i have no idea what's going on, can someone help me?

![duik](https://user-images.githubusercontent.com/93828980/227964706-4958a2fc-e870-4dd9-bb45-72bf0e21764f.jpg)
![duik2](https://user-images.githubusercontent.com/93828980/227964719-a926952d-6c5f-4b9a-a603-972ba3fed48e.jpg)

**Comment by Mitsukatsu** [comment]
thank you. you mean just precomposing the foot and than adding pins to the precomp, still inside the maincomp? unfortunately that still didn't work completely... the weird lines around the original foot position still shows up, even when i dont move the toes, just the foot in it's normal shape. ant when i have the foot in another position and move the toes, it breaks apart.
![duik3](https://user-images.githubusercontent.com/93828980/228020052-10c25785-6dfe-497c-90d8-13ddf2b70aa7.jpg)

**Comment by Nico-Duduf** [comment]
The mesh of the puppet engine is too small, maybe because you've scaled the layer, or that happens too on shape layers which aren't precomposed.

this being said, that's not an issue with Duik, I'm closing the issue here.

If you need help using Ae and Duik I suggest you come on our discord server for example: http://chat.rxlab.info
