### ISSUE TITLE
Save time and improve performance when using bones

### ISSUE THREAD

**Issue by urekmazino00** [RxLaboratory/Duik#1047]
Sometimes we do not need to use noodle and envelop, and when they are present, the auto-rig process takes a long time.
If the option to create bones without noodle and envelop is provided, this will save a lot of time and improve the after effect performance.

If only bake noodle & envelop is added, it will be useful in meta-rig since sometimes we need envelop and noodle in arms and legs

**Comment by Nico-Duduf** [comment]
Fixed: A new option to use "light bones" is available in Duik 17.0.5, in a few days

**Comment by urekmazino00** [comment]
Thanks ^^
