### ISSUE TITLE
Duik Angela stuck on rigging spine

### ISSUE THREAD

**Issue by ggandrewgg** [RxLaboratory/Duik#1056]
> Before submitting a bug report, please follow these steps which will help us diagnose your problem:

- [x] Download "DuSI": 
    A script to try to fix issues and get needed system information for debugging
- [x] Run DuSI in After Effects and click the "Fix / Uninstall" button.
- [x] Try again to run Duik and try to reproduce the bug. If it's fixed, congrats! If not, continue to the next step.
- [x] Run DuSI again and click the "Get System Information" button. It will ask you to save the info to a file. Choose one, and post it here!
- [x] Write your bug report below, and don't forget to attach the file saved by DuSI or copy/paste its content here. (it's a simple text file)

----

**Description**

I keep getting stuck on rigging the spine.  The process freezes every time no matter what I do.  I had no problem rigging then all of a sudden it just won't work.  It bakes the bones then stops at the same point each time.
![Untitled-1](https://user-images.githubusercontent.com/130376013/230918378-175ec323-9462-4044-8313-d0e6a0ca488a.jpg)

**To Reproduce**

1.make shape layers
2. attach art to bones
3. auto-rig

**Error description, if any**

File: 
Line number:
Error message: 

**Additional context**

**System information**

Drop the file generated by DuSI or copy its content here.
[test.txt](https://github.com/RxLaboratory/Duik/files/11190944/test.txt)

**Comment by Nico-Duduf** [comment]
Thanks for the report,

Can you enable the dev&debug mode in Duik settings, try again, and post the error here?

and/or post your aep as it is before you run the autorig?

**Comment by ggandrewgg** [comment]
I have turned on Dev mode.  Not getting any error messages..  This is happening to all of my AEP.  I have tried to rig from scratch and am getting the same result.

**Comment by Nico-Duduf** [comment]
Can you enable de "javascript debugging" option in the after effects Scripting settings, and post the error here?
The must be an error, if Duik freezes like this it's because of an exception in the script, we have to find which. I can't reproduce the issue here...

**Comment by Nico-Duduf** [comment]
Can you give me more details about the spine too, what are the options you're using, etc

It may be specific. Or just send me an example AEP, as requested, to check if it contains something specific to your project/settings/etc and the options you used when creating the spine.

**Comment by ggandrewgg** [comment]
I seem to have fixed the issue.  What I did was copy and paste all the script files into the scriptui folder not just the one.  Not sure why it worked but Duik now shows up twice in my windows option and it works on my project again.  I can still send all of that info you'd like though.
