### ISSUE TITLE
NON-LINEAR ANIMATION issue

### ISSUE THREAD

**Issue by francopolis** [RxLaboratory/Duik#1058]
> Before submitting a bug report, please follow these steps which will help us diagnose your problem:

- [ ] Download "DuSI": https://rxlaboratory.org/tools/dusi/
    A script to try to fix issues and get needed system information for debugging
- [ ] Run DuSI in After Effects and click the "Fix / Uninstall" button.
- [ ] Try again to run Duik and try to reproduce the bug. If it's fixed, congrats! If not, continue to the next step.
- [ ] Run DuSI again and click the "Get System Information" button. It will ask you to save the info to a file. Choose one, and post it here!
- [ ] Write your bug report below, and don't forget to attach the file saved by DuSI or copy/paste its content here. (it's a simple text file)

----

I have a complex rig with different controllers, a mix of Duik, JnS, and Limber. I get those non-Duik controllers can't work, but for some reason, NON-LINEAR ANIMATION disables it all of them. Here is a short video (no audio)
https://www.loom.com/share/3d2fc522b85f4a1497e8fa6311e8a9d5

**Error description, if any**

Scripting error shown in the video

**Additional context**

I saw in the Duik Angela course that NLA works mainly with the position, scale, and rotation properties, so why can it work with a controller outside Duik tools?

**System information**

Generated by DuSI v1.4.0

[OS]
OS:Windows/64 10.0  
Filesystem:Windows

[Host]
Host:aftereffects
HostVersion:23.3x53

[Folders]
appData:C:\ProgramData # [R,W]
appPackage:C:\Program Files\Adobe\Adobe After Effects 2023\Support Files # [R,-]
commonFiles:C:\Program Files\Common Files # [R,-]
current:C:\Program Files\Adobe\Adobe After Effects 2023\Support Files # [R,-]
desktop:C:\Users\franc\OneDrive\Escritorio # [R,W]
myDocuments:C:\Users\franc\OneDrive\DOCUMENTOS # [R,W]
startup:C:\Program Files\Adobe\Adobe After Effects 2023\Support Files # [R,-]
system:C:\Windows\SYSTEM32 # [R,-]
temp:C:\Users\franc\AppData\Local\Temp # [R,W]
userData:C:\Users\franc\AppData\Roaming # [R,W]

**Comment by Nico-Duduf** [comment]
There are two different issues here:

- The expressions in the precomp are not updated when creating the NLA. That has been already reported and will be fixed in the next version

- The NLA setups only:
  - Layers marked as Controllers (you can tag any layer of your choice as controllers, in the controller panel, to include any layer)
  - Selected properties (you can select any property to include it in the NLA)
So using other tools should not be an issue.
