### ISSUE TITLE
Add Zero tool - ALT function issue (Links and Constraints panel)

### ISSUE THREAD

**Issue by RxLab-org** [RxLaboratory/Duik#1075]
# Bug Report
Posted from https://rxlaboratory.org
## Environment
- Duik *17.0.4*
- Windows *10*
- After Effects *23.3*
### Description
The "zero property value" function holding the ALT key works only when the properties don't have keyframes. Otherwise the process freezes on the "Magic is happening!" popup.
### To reproduce
1.Select a layer that has a scale, position or rotation keyframe.
2.Click on the "Add Zero" tool in the "Links and constraints" panel while holding ALT.
3.The process freezes on the popup "Magic is happening!"

**Comment by RafaelArame** [comment]
Report on Discord.
https://discord.com/channels/480782642825134100/1096846843616448606
