### ISSUE TITLE
When I tried to link the position to the sound controller, the pick control feature doesn't work

### ISSUE THREAD

**Issue by urekmazino00** [RxLaboratory/Duik#1079]
When I tried to link the position to the sound controller, the pick control feature doesn't work.
I solved it by copying the expression, however, I think it's better to link it in the usual way.

https://user-images.githubusercontent.com/48952173/232262876-57039125-1d21-4c57-9b6e-5da693cd6a84.mp4

**Comment by Nico-Duduf** [comment]
fixed in 17.1.2
