### ISSUE TITLE
Problem with connector (link and constraints Panel)

### ISSUE THREAD

**Issue by urekmazino00** [RxLaboratory/Duik#1080]
When changing the controller to a null object, it also changes in the connector menu.

https://user-images.githubusercontent.com/48952173/232263148-bbc504d9-6e60-4975-9d75-6ea3d5dd833b.mp4

**Comment by Nico-Duduf** [comment]
fixed in 17.1.2

**Comment by RxLab-org** [comment]
Issue closed from https://rxlaboratory.org
