### ISSUE TITLE
Update Controllers from Base Comp

### ISSUE THREAD

**Issue by B-Humann** [RxLaboratory/Duik#1092]
**Is your feature request related to a problem? Please describe.**
I generally setup all the rigging in a base comp, and then extract the controllers in another comp so that I only ever have to change the art in the base comp in order to have it update throughout all the animations.  However, if I update something inside a controller (For instance, I use checkboxes to toggle visibility on different hand poses, etc) that change doesn't then populate within the comps I have extracted the controller to. 

**Describe the solution you'd like**
I would love to have a single button that you could update the FX on the controller that you have selected from the base comp it is being extracted from.

**Describe alternatives you've considered**
Currently, if I ever need to gain a new function for a controller, I simply have to make a new controller in the base comp, and then extract.  However, this also adds new locators for all the existing controllers I have already extracted, which makes it all very messy.

**Comment by Nico-Duduf** [comment]
You could manually extract the new effects: that's just adding them to the essential properties and copying them outside of the comp if you're using essential properties, or with expressions it's a really simple expression link, Duik does nothing more than that.

But implementing a way to differentiate already extracted effects from new ones is a bit complicated (if you already have other effects of the same type, and if some of them have been renamed for example, that could lead to many issues...)
