### ISSUE TITLE
The "path constraint" feature needs some improvement

### ISSUE THREAD

**Issue by urekmazino00** [RxLaboratory/Duik#1093]
https://user-images.githubusercontent.com/48952173/235314289-f87d0482-907b-49f4-bab5-2340ff0ffb7b.mp4

**Comment by Nico-Duduf** [comment]
That's the only way to make it correctly loop: 0% and 100% can't be the same point, either 0 or 100 have to be on the other end (and 200, 300, etc.). It's not really intuitive, but that can't be easily changed unfortunately
