### ISSUE TITLE
When pressing Alt, the layer is not accurately snapped above the first vertex [ Links and constraints Panel / path costraint ] 

### ISSUE THREAD

**Issue by urekmazino00** [RxLaboratory/Duik#1094]
https://user-images.githubusercontent.com/48952173/235318991-87259a53-92c5-4e73-b946-fc0dfd20fe39.mp4

**Comment by Nico-Duduf** [comment]
Hum. This is probably because the transform values of the group containing the path are not [0,0]
That's always a problem with shape layers, you can have many nested groups with different transform values.

I'll see what I can do!

**Comment by urekmazino00** [comment]
Strange problem

**Comment by Nico-Duduf** [comment]
Fixed in 17.1.4
