### ISSUE TITLE
Is it possible to have Kleaner preserve the easing of all keyframes except the last one?

### ISSUE THREAD

**Issue by urekmazino00** [RxLaboratory/Duik#1096]
I suggested this method because sometimes you have a certain animation and you use Kleaner to improve it, but you lose the settings you originally had, which wastes time resetting them.

https://user-images.githubusercontent.com/48952173/235480804-365a266e-f161-44f9-93cd-4547e7f9a2b7.mp4

**Comment by Nico-Duduf** [comment]
Yes that makes sense for some of these presets.

Presets which should preserve keyframe interpolation:

- All springs/bounces
- Limits

**Comment by urekmazino00** [comment]
I didn't understand well 😔😔

**Comment by urekmazino00** [comment]
thanks :)

**Comment by urekmazino00** [comment]
Interpolation issue when using the bounce effect, I need to separate the values from each other.
