### ISSUE TITLE
Is it possible to add an option to link each layer to the one after it using the Auto-Parent tool?

### ISSUE THREAD

**Issue by urekmazino00** [RxLaboratory/Duik#1101]
Is it possible to add an option to link each layer to the one after it using the Auto-Parent tool?
![image](https://user-images.githubusercontent.com/48952173/236647139-749f6f44-6b91-4104-beba-f26a41bc9528.png)

**Comment by Nico-Duduf** [comment]
done in 17.1.2

**Comment by urekmazino00** [comment]
Thank you
