### ISSUE TITLE
Add a button to enable/disable selected expressions (links & constraints panel)

### ISSUE THREAD

**Issue by urekmazino00** [RxLaboratory/Duik#1102]
When linking several properties in Duik to the Connector, sometimes we need to adjust a specific property in a large group of layers, which requires us to manually disable the expression in each property. If there was a feature to enable/disable expressions for selected properties, it would save us a lot of time

**Comment by urekmazino00** [comment]
I was able to implement this feature with this code and it works perfectly. I hope it helps 
```
/**
 * Enable/Disable Expression
 **/
var curComp = app.project.activeItem;
app.beginUndoGroup('enable/disable expression');

for(var i = 0; i < curComp.selectedProperties.length; i++) {
  var prop = curComp.selectedProperties[i];
  
  if(prop.expressionEnabled === true) {
    prop.expressionEnabled = false; // Disable expression
  } else {
    prop.expressionEnabled = true; // Enable expression
  }
}

app.endUndoGroup();
```

**Comment by Nico-Duduf** [comment]
Done in 17.1.2

Note that to switch, you can write this in a simpler way like this:
`prop.expressionEnabled = !prop.expressionEnabled;`

But anyway, that doesn't work as expected: you should check before the loop if the first one is enabled, and enable or disable all the expressions, not toggling them (so that after running the script, they're all in the same state)

```js
var expressionEnabled = !curComp.selectedProperties[0].expressionEnabled;
for(var i = 0; i < curComp.selectedProperties.length; i++) {
  curComp.selectedProperties[i].expressionEnabled = expressionEnabled;
}

```

**Comment by Nico-Duduf** [comment]
Other note: it will be in the Automation & expression panel (as this is where the various expression tools are)

**Comment by Nico-Duduf** [comment]
(Actually, Ctrl + Click on the remove expressions button)

**Comment by urekmazino00** [comment]
Thanks
