### ISSUE TITLE
BezierIK with custom bones issue

### ISSUE THREAD

**Issue by ThreadAndSandpaper** [RxLaboratory/Duik#1105]
Angela is behaving strangely when I try to use custom bone configurations. I'm pretty proficient with Bassel, and am trying to follow a similar workflow, but a procedure that works flawlessly in Bassel results in gobledy gook in Angela. I'm creating a 3 bone custom structure as the cheekbone of a facial rig, with the intent to use bezier IK to control it. First big difference (not sure if this is by design) I have to use a 4 segment custom bone structure in Angela (a opposed to three in Bassel.) I have exactly the same things selected. Then, when I apply the auto rig (set to bezierIK) it massively breaks the rig. The auto rig code is sending the bones all over the place and generating the controllers iin weird places too. I'm attaching a screen shot of the bones before I hit auto rig, and immediately after.  
<img width="1427" alt="Screenshot 2023-05-11 at 3 41 26 PM" src="https://github.com/RxLaboratory/Duik/assets/130402281/55aa0fb0-af5b-473b-8e16-aeba0ae62f22">
<img width="1325" alt="Screenshot 2023-05-11 at 3 42 53 PM" src="https://github.com/RxLaboratory/Duik/assets/130402281/de9a215a-56a0-4a1a-9930-ff12738f3708">

**Comment by Nico-Duduf** [comment]
Indeed, that's completely broken...

Will be fixed in the next version

**Comment by Nico-Duduf** [comment]
Fixed! The new version will be out in a couple of days at most
