### ISSUE TITLE
Problème avec les os 

### ISSUE THREAD

**Issue by RxLab-org** [RxLaboratory/Duik#1111]
# Bug Report
Posted from https://rxlaboratory.org
## Environment
- Duik *17.1.1*
- Windows *64 10.0*
- After Effects *23.1x83*
### Description
Quand je veux créer une structure, même une simple (comme un bras), Duik Ángela ne me crée pas les os. Seul les axes de rotation apparaissent. Dans l'effet Bone Data des calques, la longueur et la rotation sont à 0.

### To reproduce
1. création d'une composition
2. création d'un structure bras
### Additional context
Quand j'ai installé Duik Ángela et que j'ai fait quelques essais, tout c'est bien passé, mais en réouvrant After Effects le jour suivant et en voulant continuer à faire quelques essais, le problème est apparu.
Je n'ai fait aucune modification dans les paramètres d'After entre temps. Vu que j'avais Duik Bassel 2 d'installés j'ai essayé de voir si lui avait un problème, mais non, lui fonctionne parfaitement, les structures se crées bien.
J'ai désinstallé Duik Ángela et Bassel 2, supprimer le répertoire dans les documents, réinstallé Duik Ángela, mais le problème persiste.

Je me tourne donc vers vous pour m'aider et me tiens à votre disposition pour tout renseignement complémentaire.

Par avance merci.

Cordialement Cédric.

**Comment by RxLab-org** [comment]
Issue closed from https://rxlaboratory.org

**Comment by TomsenLee** [comment]
Hello,

I have exactly the same problem, but cant find a solution anywhere....

Did you already found a way, how to fix this problem?

kind regards
Tom
