### ISSUE TITLE
Strange Issue with Temporal Interpolation Tool

### ISSUE THREAD

**Issue by RxLab-org** [RxLaboratory/Duik#1127]
# Bug Report
Posted from https://rxlaboratory.org
## Environment
- Duik *17.1.2*
- Windows *64 10.0*
- After Effects *23.4x53*
### Description
When I try to make adjustments to the easing in the Temporal Interpolation tool, no changes occur unless I switch the keyframe to easy ease
### Error description
https://cdn.discordapp.com/attachments/1111262667080998962/1111262667546562560/Animation.mp4
### To reproduce
.

**Comment by urekmazino00** [comment]
On Discord: https://discord.com/channels/480782642825134100/1111262667080998962/1111262667080998962
