### ISSUE TITLE
Interpolator - Bounce not working

### ISSUE THREAD

**Issue by LabeyFX** [RxLaboratory/Duik#1139]
----

**Description**

The Bounce type of the extrapolator in the Interpolator effect is not working.

**To Reproduce**

1. animate a shape in position
2. Put interpolator on position
3. Switched to Sigmoid, put 100% in Extrapolation, clicked on Activate keys et chose Type Bounce. Nothing happens

**Error description, if any**

Before running DuSI i had this message error 
_After Effects warning: Expression disabled_ 
Error at line 366 in property 'Position' of layer 1 ('Rectangle') in comp 'Comp I'.
property or method named 'fThrough' in Class 'global' is missing or does not exist- It may have been renamed, moved, deleted, or the name may have been mistyped_

After running DuSI i get this message type :
_After Effects warning: Expression Disabled
Error at line 387 in property Position' of layer 1 (Rectangle) in comp tComp 1'-
ReferenceError: fThrough is not defined
var dist = - b[0]);
result = interpolationMethod(t, tMin, tMax, a, b);
if ((dist > 0.5 colorspace 2) Il (dist < 0.5 colorspace 3)_

**Additional context**

The Follow through works well

**System information**

[systeminfo.txt](https://github.com/RxLaboratory/Duik/files/11728600/systeminfo.txt)

**Comment by FrankWBaker** [comment]
Same for me. no bounce :'-(

**Comment by Nico-Duduf** [comment]
It's fixed in 17.1.4, available today or tomorrow ;)
