### ISSUE TITLE
Issue with the copy/paste animation | Animation Panel

### ISSUE THREAD

**Issue by RxLab-org** [RxLaboratory/Duik#1152]
# Bug Report
Posted from https://rxlaboratory.org
## Environment
- Duik *17.1.4*
- Windows *64 10.0*
- After Effects *23.5x52*
### Description
.
### Error description
https://cdn.discordapp.com/attachments/813164559648686110/1129365138688987147/copy-paste.mp4
### To reproduce
.

**Comment by Nico-Duduf** [comment]
Fixed in 17.1.5

**Comment by RxLab-org** [comment]
Issue closed from https://rxlaboratory.org
