### ISSUE TITLE
Issue with "add list" tool

### ISSUE THREAD

**Issue by RxLab-org** [RxLaboratory/Duik#1154]
# Bug Report
Posted from https://rxlaboratory.org
## Environment
- Duik *17.1.4*
- Windows *64 10.0*
- After Effects *23.5x52*
### Description
When using the add list tool, it changes the easing of the keyframe
### Error description
https://cdn.discordapp.com/attachments/813164559648686110/1130841548834214068/add_list.mp4
### To reproduce
.

**Comment by Nico-Duduf** [comment]
Fixed in 17.1.5

**Comment by RxLab-org** [comment]
Issue closed from https://rxlaboratory.org
