### ISSUE TITLE
Add list

### ISSUE THREAD

**Issue by RxLab-org** [RxLaboratory/Duik#1169]
# Bug Report
Posted from https://rxlaboratory.org
## Environment
- Duik *17.1.6*
- Windows *64 10.0*
- After Effects *23.3x53*
### Description
when i try to apply " Add list"  to a property "position x", de list don´t work and broke parent with other connectors.  
### To reproduce
apply "add list" to any layer in position.  the values controllers doesn´t work.

**Comment by Nico-Duduf** [comment]
Can't reproduce,
More info asked by email

**Comment by RxLab-org** [comment]
Issue closed from https://rxlaboratory.org
