### ISSUE TITLE
Script Failure Installing

### ISSUE THREAD

**Issue by RxLab-org** [RxLaboratory/Duik#1173]
# Bug Report
Posted from https://rxlaboratory.org
## Environment
- Duik *17.1.7*
- macOS *Ventura 13.5*
- After Effects *23.6*
### Description
I have uninstall After Effects and Duik Angela, with all files associated. Then installed both again. When opening Duik, After Effects will show the following prompt:  "unable to execute script at line 12651. text layers do not have a source"
I am able to install Duik 16 without problem in the same version of After Effects.
### Error description
Duik Angela 17.1.7
Line: 12651
Error: text layers do not have a source
### To reproduce
1. MacOs Ventura 13.5
2. Mac Book Pro 2023 M2 Max
3. After Effects 23.6 
4. Duik Angela 17.1.7

**Comment by Nico-Duduf** [comment]
Waiting for more details by email

**Comment by RxLab-org** [comment]
Issue closed from https://rxlaboratory.org
