### ISSUE TITLE
Problème avec les sliders de easing

### ISSUE THREAD

**Issue by LePeterAlan** [RxLaboratory/Duik#1176]
# Bug Report

## Environment

- Duik *v17.1.7*
- Windows *Windows 11*
- After Effects *23.6*

## Report

Les boutons de easing ne marchent pas toujours bien. Je n'ai pas encore totalement trouvé sur quels sliders cela pose problème, mais voilà un bug de mon côté :
Sur un texte, je met deux keyframes sur le scale, et j'applique un easing en cliquant sur les sliders de Duik.
La première keyframe n'a pas reçu le easing que je pensais recevoir.
Si je clique sur le bouton "easy ease", la keyframe a reçu le easing que je pensais recevoir à l'étape précédente.
J'ai mis des screenshots pour explication, ça sera peut-être plus simple à expliquer par des images.
![0  Init](https://github.com/RxLaboratory/Duik/assets/22474454/25fa82ae-dcde-4691-baaa-29e806f99424)
![1  Clic slider](https://github.com/RxLaboratory/Duik/assets/22474454/9510db13-fd55-43ac-8e1a-56877f781631)
![2  Clic bouton easy ease](https://github.com/RxLaboratory/Duik/assets/22474454/bfb1fabd-9b06-4524-ab92-6a5bcaf615d9)
![Duik](https://github.com/RxLaboratory/Duik/assets/22474454/1bf04c3a-4475-497f-9922-5bd4502ded26)

**Comment by Nico-Duduf** [comment]
Talking about it on Discord: https://discord.com/channels/480782642825134100/1147164854675845212

**Comment by ilyasok** [comment]
As I recall, those sliders do the easing separately. If you tweak one, but not the other, the easing will be assigned only to the corresponding side (in this case, to the ease-in part). You can assign both with the v-shaped mark to the right of the sliders
