### ISSUE TITLE
Duik — scrollable UI

### ISSUE THREAD

**Issue by Protozoan-248** [RxLaboratory/Duik#1184]
Hi!

Sometimes there is not much room to squeeze the precious Duik palette into. (For example the Animation toolset.) The possibility of scrolling to reach the tools outside of the window would be awesome.

Thanks.

**Comment by Nico-Duduf** [comment]
Hi,

this is not possible with scriptUI panels like Duik.

We're waiting for the new script engine by Adobe to be able to re-write the UI, but don't know when it will be available.
