### ISSUE TITLE
Problème d'emplacement des épingles

### ISSUE THREAD

**Issue by MaxDch** [RxLaboratory/Duik#1197]
**Description**

Je souhaite animer un "corps mou", un cou. Je prends l'outil marionnette et créer des points. Je sélectionne chaque point individuellement, de la racine jusqu'au point représentant la jonction avec une autre partie du corps. 

Je clique sur "ajouter des épingles" et les épingles sont générées à l'opposée de la position de mes points de marionnette. J'ai fais plusieurs tentatives et à chaque fois aucune épingle n'est générée à l'emplacement d'un point de marionnette, ce qui est contraignant pour animer ensuite....

Après avoir exécuté DuSi les épingles apparaissent toujours à l'opposé de la position de mes points de marionnette, j'ai également essayé avec un autre projet > calque de forme > outil marionnette > création d'un point > sélection de ce point > créer des épingles > l'épingle apparaît à l'opposé de la position du point.

**System information**

Generated by DuSI v1.4.0

[OS]
OS:Windows/64 10.0  
Filesystem:Windows

[Host]
Host:aftereffects
HostVersion:24.0x55
![Capture d’écran (5516)](https://github.com/RxLaboratory/Duik/assets/153017964/fcf4b58a-916e-4d53-b9ad-5c6e2eeb0829)

**Comment by Nico-Duduf** [comment]
Hello,
On a ce genre de problème souvent avec les calques de forme, qu'il faut *toujours* précomposer avant d'utiliser l'outil marionnette dessus, tout simplement ;)

**Comment by MaxDch** [comment]
Bonsoir,

Merci pour votre réponse et bonne année !!!

**Comment by MrPolo67** [comment]
Salut,
Je ne sais pas si ça peut aider mais...
Je suis arrivé ici car j'avais le même problème, en utilisant les calques AI que j'avais collapsé.
J'ai finalement résolu le souci en enlevant le collapse, en effaçant l'effet marionnette et en recommençant mes pins. Et ça fonctionne encore lorsque je réactive le collapse du calque ai après. 
Précision, je n'ai pas touché la position et l'échelle du calque.

**Comment by Nico-Duduf** [comment]
L'outil marionnette est un effet qui est fait pour travail sur des pixels, pas des vecteurs, c'est pour ça qu'il pose toujours plein de problèmes quand on l'utilise sur des calques de forme ou des fichiers vecto en cochant la pixellisation continue, c'est simplement pas fait pour (du tout).

La pixellisation continue et les vecteurs servent à rien de toute façon sur un calque avec des coins de marionnette, ou pire, riggé avec Duik, puisqu'il est pas scalable correctement.
Vaut mieux précomposer tout ça (en agrandissant si nécessaire avec la pixellisation continue) et mettre la marionnette sur la précomp (sans cocher le collapse, du coup, évidemment)
