### ISSUE TITLE
3D Camera Rig séparer les dimensions

### ISSUE THREAD

**Issue by ThomasDuphil** [RxLaboratory/Duik#1198]
# Feature Request

## Environment

- Duik *17.1.9*
- Windows *64 10.0*
- After Effects *24.0.3x2*

## Report

j'aime beaucoup le système de rigging de caméras de DuIK, cependant, en utilisant le rig 3D, il serait beaucoup plus agréable d'avoir des contrôleurs ayant les dimensions de position séparées. Ou bien il serait appréciable d'avoir une option pour séparer / réunir les dimensions pour voir correctement travailler les courbes d'animation dans l'éditeur de graph.

Merci ! :)

**Comment by Nico-Duduf** [comment]
C'erst fait dans Duik 17.1.10 dispo bientôt ; Duik regarde si les dimensions sont séparées sur la Caméra avant le rig, et fait de même sur les contrôleurs créés.
