### ISSUE TITLE
Can't uninstall Duik Angela

### ISSUE THREAD

**Issue by Sophilllle** [RxLaboratory/Duik#1203]
# Bug Report

## Environment

- Duik *v17.1.7*
- macOS *13.5*
- After Effects *24.0.3*

## Report

I really love duik, used Bassel a lot but I've been working with a new team for the last couple of months and they don't use it.. So now I have way too much plugins listed in my window. I juste want to uninstall it. I can't find it anywhere in my app folders. I tried to update to V17.1.11 and it added another list of Duik tools. I hade no problem to remove those (juste deleted them from my app script Ui panel) but I can't remove the older ones.. I tried DuSI too, did nothing.

I don't know what to do at this point, please help.

**Comment by Sophilllle** [comment]
How naive could I be to believe that you would help me remove your plugin!

**Comment by Nico-Duduf** [comment]
This is *not* a place for support, it's only for bug reports or feature requests.
You can either have a look at the doc or come to chat.rxlab.info which are the *only* channels where you can get help from us, when we have time to answer.
There are also many other places on the internet where you can ask for help about After Effects.
