### ISSUE TITLE
Unable to open Duik

### ISSUE THREAD

**Issue by aqiuch** [RxLaboratory/Duik#1211]
> Before submitting a bug report, please follow these steps which will help us diagnose your problem:

- [x] Download "DuSI": https://rxlaboratory.org/tools/dusi/
    A script to try to fix issues and get needed system information for debugging
- [x] Run DuSI in After Effects and click the "Fix / Uninstall" button.
- [x] Try again to run Duik and try to reproduce the bug. If it's fixed, congrats! If not, continue to the next step.
- [x] Run DuSI again and click the "Get System Information" button. It will ask you to save the info to a file. Choose one, and post it here!
- [x] Write your bug report below, and don't forget to attach the file saved by DuSI or copy/paste its content here. (it's a simple text file)

----

**Description**

I am unable to run Duik. Once I open it a pop up text saying "Unable to execute script at line 21547. After Effects error: The section name and key (Main Pref Section v2, Use Reduced Contrast) could not be found in the preferences." After closing this message Duik panel is all black.

**To Reproduce**

1.  Go to after effects "window"
2.  Search and open Duik panel
3.  Message pops up

**Error description, if any**

BUG REPORT
Generated by DuSI v1.4.0

[OS]
OS:Windows/64 10.0  
Filesystem:Windows

[Host]
Host:aftereffects
HostVersion:24.4x47

[Folders]
appData:C:\ProgramData # [R,W]
appPackage:C:\Program Files\Adobe\Adobe After Effects 2024\Support Files # [R,-]
commonFiles:C:\Program Files\Common Files # [R,-]
current:C:\Program Files\Adobe\Adobe After Effects 2024\Support Files # [R,-]
desktop:C:\Users\alisq\Desktop # [R,W]
myDocuments:C:\Users\alisq\Documents # [R,W]
startup:C:\Program Files\Adobe\Adobe After Effects 2024\Support Files # [R,-]
system:C:\Windows\SYSTEM32 # [R,-]
temp:C:\Users\alisq\AppData\Local\Temp # [R,W]
userData:C:\Users\alisq\AppData\Roaming # [R,W]

File: 
Line number:
Error message: 

**Additional context**

**System information**

Drop the file generated by DuSI or copy its content here.

**Comment by Nico-Duduf** [comment]
This looks like a bug which was fixed some time ago. Please make sure you're using the latest version of Duik.

**Comment by ITNinja01** [comment]
My customer uses DUIK with After Effects on Windows 11 and is getting a similar error:  Unable to execute script at line 21565.... when trying to run it. 

I found a form from Adobe saying the issue is with a Beta UI theme and suggesting to contact you:

https://community.adobe.com/t5/after-effects-discussions/duik-angela-unable-to-execute-script-at-line-21565/td-p/14626394
 
I have updated him to 17.1.16.

**Comment by Nico-Duduf** [comment]
Hi,

This has been fixed a few versions ago.
Please double check you've correctly installed v17.1.6

**Comment by Nico-Duduf** [comment]
Hi,

This issue is fixed in 17.1.16.
If there's still the same error, it means it hasn't been correctly updated.

Le 19 septembre 2024 16:35:18 GMT+02:00, ITNinja01 ***@***.***> a écrit :
