### ISSUE TITLE
Unable to execute script at line 21565

### ISSUE THREAD

**Issue by WestWIndStudio** [RxLaboratory/Duik#1218]
![ERROR MESSAGE](https://github.com/RxLaboratory/Duik/assets/172491074/c7318b9a-b978-4812-871a-cb8918a30314)
# Bug Report

## Environment

- Duik *v17.1.3*
- macOS *Sonoma 14,5*
- After Effects *24.4.1*

**Comment by WestWIndStudio** [comment]
Hey,

Cant open Angela Duik. I ve unistall, reinstall many times but it brings that same error message all the times.

Thanks in advance!

**Comment by Nico-Duduf** [comment]
Hi,
You're not installing the latest version, this has already been fixed ;)
