### ISSUE TITLE
WE WANT DUIK BASSEL BACK! Why are they depriving us of the possibility of downloading old versions? duik angela is not working properly and i just want to use duik bassel :c

### ISSUE THREAD

**Issue by exf2027** [RxLaboratory/Duik#1219]
# Feature Request

## Environment

- Duik *v16.2.30*
- macOS *-*
- After Effects *-*

**Comment by Nico-Duduf** [comment]
Please don't be rude, that's not the way we talk to people here.
Duik Bassel **is available** from the official download page, and here on Github.
