### ISSUE TITLE
Duik 16 Bassel doesn't work in the Latest AE

### ISSUE THREAD

**Issue by armax9** [RxLaboratory/Duik#1222]
When I open Duik 16 in the new AE, I have this error, which happens due to updated AE interface. I know it's already fixed in the Duik 17, but is there any chance we can get the update for Duik 16? Or support of it completely dropped?

For some tasks I feel that with Duik 16 I can work faster than with Duik 17. Would be sad if with the latest AE updates we'll loose Duik 16 forever.

Error:
After Effects (Beta)
Unable to execute script at line 10069. After Effects (Beta) error: This
color id is invalid.

**Comment by Nico-Duduf** [comment]
Hi,

We don't have time to maintain older versions of our tools, but as it's free and open source anyone is welcome to submit a patch!

You could also file some feature requests here so we can understand why Duik Bassel would be better than Angela, which specific features would need to be improved (or come on our discord server on http://chat.rxlab.info to talk about it)
