### ISSUE TITLE
Baking comp cancels path animation connected to a slider

### ISSUE THREAD

**Issue by ilyasok** [RxLaboratory/Duik#1223]
**To Reproduce**

1. Create a path animation
2. Tie the animation to a slider
3. Bake the comp (smart mode, or precise -- no matter)

Archived project is in this message, to reproduce the bug within it
1. Duplicate Comp in 'Precompose/2_Waiting_RIG'
2. Use bake function

Workaround has been found: converting expression to keyframes on the path before baking it

**Additional context**

I've been working on some lottie animations and used duik for it. It's really handy with its baking feature. Sometimes, though it produces unexpected results (usually in smart mode), breaking limbs and so on, but it was manageable until this happened.

**System information**

Generated by DuSI v1.4.0

[OS]
OS:Windows/64 10.0  
Filesystem:Windows

[Host]
Host:aftereffects
HostVersion:23.0x59

[Folders]
appData:C:\ProgramData # [R,W]
appPackage:C:\Program Files\Adobe\Adobe After Effects 2023\Support Files # [R,-]
commonFiles:C:\Program Files\Common Files # [R,-]
current:E:\Работа\240610_РИЧ+Плайт_Анимация персонажа в Lottie\2_Рабочие файлы (AE,Rive)\2_Comps # [R,W]
desktop:C:\Users\ilyam\Desktop # [R,W]
myDocuments:C:\Users\ilyam\Documents # [R,W]
startup:C:\Program Files\Adobe\Adobe After Effects 2023\Support Files # [R,-]
system:C:\WINDOWS\SYSTEM32 # [R,-]
temp:C:\Users\ilyam\AppData\Local\Temp # [R,W]
userData:C:\Users\ilyam\AppData\Roaming # [R,W]
[2_Waiting_ForDuik_Troubleshooting folder.zip](https://github.com/user-attachments/files/16599884/2_Waiting_ForDuik_Troubleshooting.folder.zip)

**Comment by Nico-Duduf** [comment]
Fixed in 17.1.17 available soon
