### ISSUE TITLE
Attach layer to bezier path doesn'tuse layer pos or rot

### ISSUE THREAD

**Issue by Jissse** [RxLaboratory/Duik#308]
# Environment
### Tool & Version
- Duik 16.0.1-Alpha-5

### After Effects
- CC2018 (15.0)
- English

### OS
- Windows 7

# What's the issue?
- Enhancement

### Steps to reproduce
When using the "attach to bezier path" command it doesn't use the position or rotation of the layer with the path.
You have to line up the thing your attached by hand.

**Comment by Nico-Duduf** [comment]
Done!
