### ISSUE TITLE
Flop/Flip button (flops the scale of the layer with a checkbox)

### ISSUE THREAD

**Issue by Nico-Duduf** [RxLaboratory/Duik#336]

**Comment by KyuneLam** [comment]
i would love to have a flip checkbox for the whole rig, but also for individual limbs, for example leg/shoe rig

**Comment by Nico-Duduf** [comment]
This is another feature, which has been in the todo list for a long time, but it's low priority as there are good workarounds:

flipping a whole character can be done easily if it is precomposed (and controllers are extracted to ease animation)
and flipping a single limb is usually done by rigging a copy and using opacities to switch between the two. This easily allows to have a different design for each side.
