### ISSUE TITLE
FR: Bones for paths to include a lock for handles

### ISSUE THREAD

**Issue by reneandritsch** [RxLaboratory/Duik#369]
### Tool & Version
- Duik 16.1.0-Beta

### After Effects
- CC2018 (15.1.2)
- English

### OS
- Mac OS 10.13.6

# What's the issue?
- Feature Request

Being used to manipulating paths in AE and Illustrator it would be great to have an option to lock the tangents of the handle controllers to maintain a good curve when using the bones on a path. Maybe this could be done with a checkbox that enables an expression to tie the values of the to handles together. Please see my mockup in the screen capture.

Thanks a lot, René

![tangents](https://user-images.githubusercontent.com/38455050/50182896-d6d2a580-0310-11e9-9fef-ef3a01405cee.gif)

**Comment by reneandritsch** [comment]
Just today I had another idea. Maybe that’s of more use. As you can rotate the handles with the bone it would nonetheless be great to have the possibility to lock the tangents. Because moving one of the handles would break the smooth curve. To get back to the smooth curve a “Lock tangent” checkbox would be nice to set it to the “inverse” values of the respective handle.

![lock](https://user-images.githubusercontent.com/38455050/50835598-6c34e880-1357-11e9-90a3-3f023e287fdc.gif)

**Comment by reneandritsch** [comment]
The only problem might be that the handle that has the lock checkbox can not be moved – at least in what I did in my mock-up.

**Comment by Nico-Duduf** [comment]
Yes I thought about that. Maybe hiding the one which is locked could work?

**Comment by Nico-Duduf** [comment]
Done in Ángela

**Comment by reneandritsch** [comment]
Thanks a lot! I still have to try all the new amazing things you implemented!
