### ISSUE TITLE
Random Wiggle for multiple layers

### ISSUE THREAD

**Issue by armax9** [RxLaboratory/Duik#580]
Hello Nico!

That feature was working in Duik 15 and it was great.

For example, if I have 25 layers, and want to wiggle them with Unified Control, same parameters (amplitude, frequency), but different "Random Seed" for each layer.

I mean, now if you are wiggling multiple layers, they are moving in same way.
That works only if you have Shape Layer with big amount of layers inside of it. But that gives limitations for creative solutions.
Please see the video (60 sec) - https://youtu.be/CQReaOM5QIY

Only possible solution for now - wiggle all 25 layers with Individual controls and change "Random Seed" of every layer, and it takes a lot of time.

What do you think, is this possible to implement?

**Comment by Nico-Duduf** [comment]
The random seed for individual controls should be different for each layer, it should be initialised with the index of each layer. If it's not the case let me know, it's a bug.

That said, It would be nice to have a checkbox for a "one seed per layer" option, I'll add this

**Comment by armax9** [comment]
Yes, it works with Individual controls, but needs a lot of time to set different seed for each layer. Checkbox for different seed would be great, thank you!

**Comment by Nico-Duduf** [comment]
Done in Ángela
