### ISSUE TITLE
Extract Controller

### ISSUE THREAD

**Issue by mkgrafics** [RxLaboratory/Duik#656]
**Describe the bug**
Extracting controllers when using Master properties.

**To Reproduce**
1. 
2. 
3. 

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: windows
 - Version of After Effects: 2020
 - Version of Duik: 16.2.8

**Additional context**

[extract.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/4353832/extract.zip)

**Comment by Nico-Duduf** [comment]
posted on the forum too:
http://forum.rainboxlab.org/viewtopic.php?f=11&t=1135

other files:
https://drive.google.com/open?id=1muWHC0b3xnipKq7c4rtmYZQa_8ftczij

**Comment by Nico-Duduf** [comment]
mkgrafics I don't understand your issue, in the project you uploaded, controllers have been extraced using expressions.
And everything works well here when I extract using master properties. Could explain and ass some context?....

**Comment by Nico-Duduf** [comment]
same issue as #970
