### ISSUE TITLE
Scaling / flexible bones in Tail feature.

### ISSUE THREAD

**Issue by kotydwa76** [RxLaboratory/Duik#747]
Would it by possible to make in some future versions a stretching option? To animate te lenght of the, say, a tentacle by changing the lenght of the bones. 

Imagine an octopuss-like tentacle which can shrink or stretch a bit. A little "Squash and stretch"

In the cartoonish way it would look something like this:
![126e31d569b34ce17a98e5a94262e2df](https://user-images.githubusercontent.com/72746131/96017964-ed81af00-0e4a-11eb-9498-74e8651489cb.png)

**Comment by Nico-Duduf** [comment]
Done in Duik 17 Ángela, available soon
