### ISSUE TITLE
**Extract** doesn't work on opacity layers AF 2018

### ISSUE THREAD

**Issue by AlexV3d** [RxLaboratory/Duik#826]
**Describe the bug**

**To Reproduce**
1. Have some mouth poses and connect them together through a opacity connector. 
2. Extract the controller in another composition  

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**

The controller should have been extracted to that composition and then extract it again to a bigger composition.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/83251411/116158254-02db6e00-a6f7-11eb-96c4-bfc78bcc2efe.PNG)

**System (please complete the following information):**
 - OS: Win 8.1
 - Version of After Effects:  15.1.1
 - Version of Duik: v16.2.29 

**Additional context**
Before this error happened I had a another slider of that kind but when I extracted it 2 times from composition to composition the last one didn't worked and then I deleted the slider, upgraded the Duik version(before i had the version before this one) and then tryed again to build a new slider and when I transfer it 1 time from comp to comp it froze the program and a lot of error appeared

**Comment by Nico-Duduf** [comment]
Thanks, I'll have a look; extracting controllers twice has always been difficult...

In the meantime, I think in your case you don't really need that: the controller you're connecting does not need to be in the same comp in the first place. You can connect from your main comp to the mouthes in the precomp.
