### ISSUE TITLE
Blink automation option

### ISSUE THREAD

**Issue by Jissse** [RxLaboratory/Duik#858]
An option to add randomness to the blink automatrion, something akin to

if(wiggle(5, 50) > 50) 100;
else 0

But maybe with the way to control the amount of fuziness, betweeen perfectly regular and completely random ?

**Comment by Nico-Duduf** [comment]
Bon ça ferait ramer à mort, je vois pas d'option légère, MAIS maintenant on peut animer la fréquence du blink/swing/wiggle, donc ça peut se faire en mettant quelques keyframes dans la féquence
