### ISSUE TITLE
Search... only

### ISSUE THREAD

**Issue by MrPolo67** [RxLaboratory/Duik#873]
**Describe alternatives you've considered**

Hello Duduf and Rainbox, 
On the "Search and replace"  tool in Duik v16.2.30, 
I don't know if it is possible, can we have a "Search" function with number of occurences and "next" and "previous" buttons ?
It would very useful for expressions ^^

Thanks a lot

**Comment by Nico-Duduf** [comment]
That's a good idea, but the ideal would be to select the occurences in the UI of After Effects, and scripts can't do that...
There could be some kind of indication in duik's panel, like the name of the layer and the corresponding property, but that would not be very friendly...
I'll see what can be done...
