### ISSUE TITLE
Change duration of nested comps on layers

### ISSUE THREAD

**Issue by VadimGatsula** [RxLaboratory/Duik#886]
**Is your feature request related to a problem? Please describe.**
I have short duration of my templates-precomps for my shot - so I need to increase all child precomps and layers by my hands. 

**Describe the solution you'd like**
Magic button in the tools section, that can change the one or selected layers duration (maybe with option of recursion to change duration layers inside them (nested) too).

**Describe alternatives you've considered**

**Additional context**
![deftones lipsync2](https://user-images.githubusercontent.com/57633648/155221494-2fb2e229-485f-4798-9cb2-067daac29cd8.jpg)

**Comment by Nico-Duduf** [comment]
Done in Duik Ángela, using the new "Comp Settings" section of the tools
