### ISSUE TITLE
2d camera seem can not work with AE 22.3

### ISSUE THREAD

**Issue by siyexa2951** [RxLaboratory/Duik#900]
Duik 16.2.30
Layer appear but not affect 🤔

**Comment by Nico-Duduf** [comment]
Hi,
Can you give more details please? A screenshot or video capture of your comp and timeline would be great to see what's going on.
Thanks

**Comment by siyexa2951** [comment]
My bad,I reinstall ae and duik ,and it work again .
thank you for replay :)
