### ISSUE TITLE
bug report on Duik

### ISSUE THREAD

**Issue by gonmansilla26** [RxLaboratory/Duik#901]
**Describe the bug**
In the section CONECTORS -> Property -> AXIS ... the bug is the program dont showme (any more) the window to select value X or Y.

**Screenshots**
![Sin título](https://user-images.githubusercontent.com/104153414/164487790-0980a803-0f14-4599-ac33-f3dc849d1c90.png)

**System (please complete the following information):**
 - OS: 
 - Version of After Effects: 2022
 - Version of Duik: v16.2.30

**Comment by Nico-Duduf** [comment]
Hi,
On your screenshot you selected the Y position, so Duik doesn't allow you to select the axis. That's because the dimensions must be separated in your timeline.
