### ISSUE TITLE
Wiggle, linear between frequencies keyframes

### ISSUE THREAD

**Issue by MrPolo67** [RxLaboratory/Duik#905]
Hello,
Using the Wiggle button, the evolution between two keyframes of the frequency is chaotic, and this is normal. 

But is it possible to include an expression that fixes this problem and that the interpolation between two frequency keyframes is linear?
Like Dan Ebberts did in the link below

www.motionscript.com/articles/speed-control.html
Thank you

**Comment by Nico-Duduf** [comment]
I'll see if that can be done with the current way Duik does the (looping) wiggle as soon as I have some time, thanks for the suggestion.

**Comment by Nico-Duduf** [comment]
Available in Duik Ángela
