### ISSUE TITLE
Whenever auto rig registers a rig with a head it breaks the parent/link function on the bone recognized as a head

### ISSUE THREAD

**Issue by ssyrf** [RxLaboratory/Duik#909]
**Describe the bug**

Whenever I auto-rig a model and the auto-rig function finds a bone it thinks is a head, it completely disables the link function for said bone. It disables the ability to be affected by *ANY* linked object in after effects. It can however still be a parent of objects, just it cant follow a parent. If I make an auto-rig and it doesn't find any head, everything functions properly.

**To Reproduce**
1.  Create any bone structure with a head
2.  Auto-rig said structure
3.  Try to have the bone recognized as the "head" be linked to another object

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**

The bone to be able to move alongside a parented object

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: 22.3
 - Version of Duik: 16.2.30

**Additional context**

**Comment by Nico-Duduf** [comment]
The autorig adds some expressions in the position (and propbably rotation) of the head, which overwrite the transform it gets from its parent.
Just remove these expressions if you wish to rig the head in a different way
