### ISSUE TITLE
KBar/Headless support for direct application of features

### ISSUE THREAD

**Issue by GOvEy1nw** [RxLaboratory/Duik#914]
**Describe the solution you'd like**
It'd be great if Duik worked with KBar so we could add buttons to directly apply things from Duik such as Wiggle, Kleaner, Swing, Blink etc. This would mean we wouldn't need the full Duik panel open when we only need quick access to those kinds of features.

Many thanks!

**Comment by Nico-Duduf** [comment]
Duik 17 is coming soon with an API and a few examples to let people easily create their own headless scripts using duik features, for example to include them in KBar.
