### ISSUE TITLE
DUIK Bassel 2 v16.2.30 Orientation Constraint missing

### ISSUE THREAD

**Issue by SteveNorman94** [RxLaboratory/Duik#915]
Hi, i'm wondering if the latest updates of Duik Bassel 2 doesn't have anymore Orientation Constraint in the Links & Constraints Menu. Is it gone or it's been moved somewhere else?

**Comment by Nico-Duduf** [comment]
Hi,
Check the mode of the UI in the settings, you may be in "Rookie" mode where the orientation constraint in hidden.
