### ISSUE TITLE
Clicking the “Default Settings” button prompts script error

### ISSUE THREAD

**Issue by reneandritsch** [RxLaboratory/Duik#917]
**Describe the bug**
When clicking the default settings button a script error message is showing repeatedly as long as the DUIK panel is open.

**Expected behavior**
no error message

**Screenshots**
Please see attached screen capture.

https://user-images.githubusercontent.com/38455050/169311158-65ee4591-8d06-4ab7-b881-15d28c7126e9.mov

**System (please complete the following information):**
 - OS: macOS 12.3.1
 - Version of After Effects: 22.3.0
 - Version of Duik: Angela 17.0.0-BETA1

**Comment by Nico-Duduf** [comment]
Fixed in Beta3
Thanks for your feedback!
