### ISSUE TITLE
Improwed Wiggle.

### ISSUE THREAD

**Issue by GQZ1** [RxLaboratory/Duik#918]
**Is your feature request related to a problem? Please describe.**
Wiggle - hold

**Describe the solution you'd like**
Add hold functionality to a Wiggle expression.

**Describe alternatives you've considered**
Mt Mograph 3 - have hold wiggle, but don't have loop wiggle like DUIK does. 

**Additional context**
desired effect
https://gifyu.com/image/SxE8v

**Comment by Nico-Duduf** [comment]
It's the new "Random motion" in the automation; which will get a frequency value in Beta3 soon.

In the meantime you can also just add `posterizeTime(freq);` at the beginning of the wiggle expression
