### ISSUE TITLE
Misplaced Bones from puppet pins

### ISSUE THREAD

**Issue by Damax13** [RxLaboratory/Duik#922]
When i create a tail and place it on a layer, add pins and click on add bones – those are placed way away from the pins. 

<a href="https://ibb.co/3r7sfrD"><img src="https://i.ibb.co/NVs31V8/Screenshot-2022-05-24-at-16-17-17.png" alt="Screenshot-2022-05-24-at-16-17-17" border="0"></a>

**Comment by Nico-Duduf** [comment]
Hi

that's a known issue for some shape layers; my advice is to *never* use the puppet tool on shapes anyway, as it's a pixel effect, there are a lot of issues using it on vectors. You should precompose the shape layer first and rig the precomp, that works well!
