### ISSUE TITLE
Multilayer frame copy/paste doesn't work the way it did anymore

### ISSUE THREAD

**Issue by VTom1968** [RxLaboratory/Duik#924]
**Describe the bug**
The copy and paste buttons in the Duik Animation panel have ceased to work

**To Reproduce**
1. Create twelve video layers
2. Create like eighty keyframes, distributed over the layers, in transform properties
3. Select all of these keyframes in one lasso selection and press copy, move timeline cursor and press paste

**Error description, if any**
No error

**Expected behavior**
The copying and pasting of many keyframes over several layers at the same time always worked fine, I guess I expected it still to work fine

**Screenshots**
![image](https://user-images.githubusercontent.com/107189530/172841603-df6052b8-ac89-4a7e-8d7b-7ebeba9781ed.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: 22.4.0
 - Version of Duik: 16.2.30

**Additional context**

**Comment by Nico-Duduf** [comment]
I don't see any reason why it would stop working; maybe there's something specific in this comp, can you post your project so we can run some tests?
Thanks

**Comment by VTom1968** [comment]
Hi Nicolas,

I’m very honored to receive an answer from you personally, whose work I respect and admire greatly. 
Indeed it must be something in the comp, it just beats me what it could be. 
I will send a copy of the comp as soon as possible, somewhere during the weekend or right after. 
If you could indeed have a look at it, I would appreciate this very, very much.
I am sure this issue can be solved, overall the Duik tool is rock solid when used properly and the best addition ever to a program like AE. It’s a totally fantastic job you and your colleagues have done, I can not emphasize this enough. 

I will report back soon. 

With gratitude,

Tom Verweij




Verstuurd vanaf mijn iPhone

**Comment by Nico-Duduf** [comment]
Hi,
I didn't get the aep, email attachements are not forwarded to Github, you'll have to come post it directly on the website.

Thanks

**Comment by VTom1968** [comment]
Hi Nicolas, sorry for the long wait, I got ill.
Anyway, here is the .aep file as a zip. I hope you will encounter the same error as I did, e.g. not being able to copy all keyframes from all layers and paste them again. Looks like memory gets stuck or something.
Any comment is greatly appreciated!
Kind regards, Tom
[NoCopyPaste.zip](https://github.com/RxLaboratory/Duik/files/9002610/NoCopyPaste.zip)

**Comment by Nico-Duduf** [comment]
Hi,
The problem is with the *Liquify* effect, its values can't be copied. (That's a limitation from Ae);
In Duik Ángela (17) these properties will be silently ignored instead of stopping the script.
