### ISSUE TITLE
Looper in DUIK Angela Beta 3 - does not work

### ISSUE THREAD

**Issue by GQZ1** [RxLaboratory/Duik#928]
**Describe the bug**
Looper doesn't work

**To Reproduce**
1. select 2 or 3  animated frames, and press **looper** button, nothing happens, doesn't loop. 
2. 
3. 

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**
expected animation to loop

**Screenshots**

**System (please complete the following information):**
 - OS: Win 64
 - Version of After Effects: 22.4.0
 - Version of Duik: 17 Beta 3

**Additional context**

**Comment by Nico-Duduf** [comment]
fixed in Beta4!
Thanks for the feedback
