### ISSUE TITLE
Bones and Controllers as Nulls

### ISSUE THREAD

**Issue by rickswah** [RxLaboratory/Duik#935]
**Is your feature request related to a problem? Please describe.**

Hello! I believe I'm not the first one to request to bring this feature again from the Duik v15 haha. Would be good to have these options back as they goes ease on the rendering part, as AE doesn't have to bother rendering the drawings and handling all the extra expressions that are attached to the shapes (I'm aware that you can bake the bones, but it still goes heavy on processing anyway).
The greatest advantage of Nulls over shapes is the fact that they are easy to hide, you can use the shortcut and whenever you're going to do a ram preview they goes away, and also they don't get in front of the characters while animating, which can be very annoying.

thanks for reading my message!
much love, Ricardo

**Comment by Nico-Duduf** [comment]
It's still in the roadmap though!

**Comment by Nico-Duduf** [comment]
done for controllers, can't do for bones!
