### ISSUE TITLE
Rigging bug when importing one After Effects project into another

### ISSUE THREAD

**Issue by ianwebsterOS** [RxLaboratory/Duik#938]
When receiving separate After Effects projects from animators we combine them. At the moment we are experiencing a bug with some random rigs whenever importing a project into another. To clarify, when opening an animators project all the rigs will be fine - but when that project is imported into the main 'combined' project, some of the rigs become messed up (shown in screenshot).

There are no error codes given.

**System (please complete the following information):**
 - OS: MacOS Monterey 12.4
 - Version of After Effects: Version 22.5.0 (Build 53)
 - Version of Duik: v16.2.30
<img width="294" alt="Normal" src="https://user-images.githubusercontent.com/109975378/180815446-60a20d85-21ab-48db-89b9-0e2577a11ee6.png">
<img width="543" alt="MessedupRigs" src="https://user-images.githubusercontent.com/109975378/180815460-db49d85e-1493-466e-a2d1-1ec162ea491f.png">

**Comment by Nico-Duduf** [comment]
Hi,

First thing to check is to make sure all comps have different names... If you're importing a project with comps having some names already in use that may mess things up, AE is very touchy about that, and it's a big pain.

I'd suggest to just render the animated characters before importing them, this way you won't have this kind of issues, and it'll be much better for the performance.

You can come to our discord server to continue the discussion! it's on http://chat.rxlab.info

I'm closing this issue for now as it doesn't seem to be a bug in Duik.

**Comment by ianwebsterOS** [comment]
Thanks. It doesn't seem to be the name issue as we've looked into that.

We've always worked with After Effects and Duik in this way and this is the first time we've seen this issue.

**Comment by Nico-Duduf** [comment]
Can you send me the AEP so I can I have look? and maybe a few characters aep too?

**Comment by ianwebsterOS** [comment]
We seem to have found a fix. We rolled back to After Effects version 22.3, then reupdated to 22.5. It seems to have fixed the issue.
