### ISSUE TITLE
Resizing Comps still not working with DUIK beta 6 version

### ISSUE THREAD

**Issue by andreastanner** [RxLaboratory/Duik#953]
Resizing comps is still not working with the beta 6 version... just tried it with several rigs but it's always making a mess when changing comp size.
![Screenshot 2022-08-15 161715](https://user-images.githubusercontent.com/55541491/184652569-418a9b23-2e57-49a7-b1e8-f1b131b89bbe.png)

**Comment by andreastanner** [comment]
It's working when choosing the left top arrow in comp settings.

**Comment by andreastanner** [comment]
Alright, thank's Nicolas :)

**Comment by Nico-Duduf** [comment]
Fixed in Beta7
