### ISSUE TITLE
Auto-rig proceed indicator is not disappearing 

### ISSUE THREAD

**Issue by andreastanner** [RxLaboratory/Duik#954]
When creating, for example, a plantigrade leg and front leg and then select all bones and click on "auto-rig", the finishing starts. But sometimes the proceed indicator is not disappearing after all... sometimes it does but even after disappearing, it's opening again and the only way to close it is to close after effects.

![Screenshot 2022-08-16 092630](https://user-images.githubusercontent.com/55541491/184822384-fae89f37-e96e-4b74-b09b-43829a4a0490.png)

**Comment by Nico-Duduf** [comment]
That's another AE bug I can't find a way to work around...
I'm looking for another way to show the progress, or just completely remove this kind of feeback...

**Comment by andreastanner** [comment]
Would be really nice, thank you very much

**Comment by Nico-Duduf** [comment]
It *may* be fixed in Beta7, we'll see. At least here it seems to be working but we'll need more testing as it's a bit random
