### ISSUE TITLE
Problem installing dulk effect in After Effects

### ISSUE THREAD

**Issue by azbil1118** [RxLaboratory/Duik#962]
[](url)DUIK_Two_Layer_lk

After downloading the effect and trying to install it in Adobe after affects message appears

Sorry This folder dons not contain a vlid installation of after effects 

You can see the pictures to know more About the  problem 
 
![9F858998-280E-41
![0B07102D-4647-4B2E-AD9E-FBE0BC4BCA32_1_105_c](https://user-images.githubusercontent.com/115048094/193949082-05bc07f4-d813-4ace-9081-b7fb5d742abf.jpeg)

![70D78435-3C13-4940-BCBD-A4B7C130DF86](https://user-images.githubusercontent.com/115048094/193949067-d9058bf9-5aa4-4af9-b23a-26b630eafd0e.jpeg)
E6-97B6-4DD803A721AB_1_105_c](https://user-images.githubusercontent.com/115048094/193949049-4dad0019-4cae-42dc-8da7-ad317d92a980.jpeg)

**Comment by Nico-Duduf** [comment]
Sorry, we don't provide support for (very) old versions of Duik
