### ISSUE TITLE
Decolonize our technical vocabulary

### ISSUE THREAD

**Issue by MrPolo67** [RxLaboratory/Duik#969]
Hello friends,
Using the "connector" in "Links and constraints" in english and french version (v17.0.0-Beta7), I saw names that I thought had disappeared : "slave" and "master". (esclave et maître)

Could we replace them with new words ? "child" and "parent" for exemple? (enfant et parent)

You do what you want but I personally prefer. Karl and Angela would be proud of it ! <3 <3 :) 
Cheers

**Comment by Nico-Duduf** [comment]
For now, I think "slave" and "master" are easier to understand, compared to "child" and "parent", for two reasons:
- "parent" is used for layers, and using it for properties may be confusing
- in a "child/parent" relationship (in animation software in general), although the child follows the parent, it can still be animated/controlled by the animator, whereas with the connector and a "slave/master" relationship, the slave can't do anything by itself.

I'm open to a change of vocabulary, but not at the cost of preciseness; Duik is hard enough already to learn.

On a side note, I also don't really understand this need of removing this vocabulary, and who would be offended by it; but that's a cultural matter. Here in France society just doesn't care about it. I know it's different at least in the US though.
