### ISSUE TITLE
Extract controllers fails

### ISSUE THREAD

**Issue by AweDeus** [RxLaboratory/Duik#970]
**Description**

I just CANT, i use "extract" in any mode and script just create new comp and stuck on "magic is happening" screen.

**To Reproduce**

1. Install AE2023 from scratch
2. Install Duik angela beta 6
3. create comp and place it in another one
4. make controller in that comp
5. go in parents comp and press extract in duik angela

**System information**

[21.txt](https://github.com/RxLaboratory/Duik/files/10050352/21.txt)

**Comment by Nico-Duduf** [comment]
Thanks for the report.

There's something I don't understand: what you describe is what happen with Duik Bassel (which creates the "magic is happening" comp) but in your process you mention Duik Ángela?

**Comment by AweDeus** [comment]
> Thanks for the report.
> 
> There's something I don't understand: what you describe is what happen with Duik Bassel (which creates the "magic is happening" comp) but in your process you mention Duik Ángela?

"magic is happening" it is text line on loading window that appears in Duik Angela... Its not about duik bassel at all, Basel also dont extract controllers on new AE versions, but ive made tiket about new beta verion.

**Comment by Nico-Duduf** [comment]
I just can't reproduce the issue, can you enable javascript debugging in after effects (scriptint & expressions preferences) and the "dev & debug mode" in Duik, and post here the error which should be shown when extracting the controllers?

Also, are you using expressions or essential properties?

**Comment by Nico-Duduf** [comment]
more info in #1007
