### ISSUE TITLE
Create Controller manually works not every time

### ISSUE THREAD

**Issue by andreastanner** [RxLaboratory/Duik#975]
Somehow, when I want to create for example a camera controller manually, it's not working. I just see the "magic is happenig" panel but it won't disappear. Close AE and reopen sometimes helps. 
![Screenshot 2022-12-08 082705](https://user-images.githubusercontent.com/55541491/206385187-53ee2d28-4260-4024-895f-5c213815b997.png)

**Comment by Nico-Duduf** [comment]
I can't reproduce the issue...

I'm keeping the ticket open here. In the meantime, you can check enable the 'script debugger' in the scripts settings of After Effects, and enable the 'dev & debug' mode in Duik settings, that should show an error with more details next time it fails, and give us a clue about what's wrong

**Comment by andreastanner** [comment]
Yes sure, here's the error. I just made, for example, a camera and tried to CTRL-Click to the Camera Controler Icon for direct linking.
![Screenshot 2022-12-20 075953](https://user-images.githubusercontent.com/55541491/208603337-9756fbc2-e575-4ece-82be-9432f7b7bc43.png)

**Comment by Nico-Duduf** [comment]
Oh I understand, it's an issue with cameras and lights.
Fixed for the final release, *soon* ;)

Thanks for the feedback (you can deactivate the debug mode ;) )

**Comment by andreastanner** [comment]
Great :)!!! Thanks very much nicolas!
