### ISSUE TITLE
after effects keyframes copy to paste adds jiggles

### ISSUE THREAD

**Issue by selster** [RxLaboratory/Duik#976]
1. move the timeline indicator into the future, select of the last keyframes from different layers, in the DUIK Basel plug-in hit copy and then paste,the keyframes are pasted where the timeline point is, just fine
2. if I use k and j to move back and forth, the paste looks perfect,
3. if I hand spool through the timeline, from the previous keyframe to the next, inevitably one of the keyframes will be doing some jiggling about, disconcerting for guitar students who are trying their best to emulate the animation of chords changes
4. Thanks,
5. Steve Elster
6. steven.elster1@gmail.com

Generated by DuSI v1.4.0

[OS]
OS:Windows/64 10.0  
Filesystem:Windows

[Host]
Host:aftereffects
HostVersion:23.0x59

[Folders]
appData:C:\ProgramData # [R,W]
appPackage:C:\Program Files\Adobe\Adobe After Effects 2023\Support Files # [R,-]
commonFiles:C:\Program Files\Common Files # [R,-]
current:C:\Program Files\Adobe\Adobe After Effects 2023\Support Files # [R,-]
desktop:C:\Users\steve\Desktop # [R,W]
myDocuments:C:\Users\steve\Documents # [R,W]
startup:C:\Program Files\Adobe\Adobe After Effects 2023\Support Files # [R,-]
system:C:\windows\SYSTEM32 # [R,-]
temp:C:\Users\steve\AppData\Local\Temp # [R,W]
userData:C:\Users\steve\AppData\Roaming # [R,W]

> Before submitting a bug report, please follow these steps which will help us diagnose your problem:

- [ ] Download "DuSI": https://rxlaboratory.org/tools/dusi/
    A script to try to fix issues and get needed system information for debugging
- [ ] Run DuSI in After Effects and click the "Fix / Uninstall" button.
- [ ] Try again to run Duik and try to reproduce the bug. If it's fixed, congrats! If not, continue to the next step.
- [ ] Run DuSI again and click the "Get System Information" button. It will ask you to save the info to a file. Choose one, and post it here!
- [ ] Write your bug report below, and don't forget to attach the file saved by DuSI or copy/paste its content here. (it's a simple text file)

----

**Description**

**To Reproduce**

1. 
7. 
8. 

**Error description, if any**

File: 
Line number:
Error message: 

**Additional context**

**System information**

Drop the file generated by DuSI or copy its content here.

**Comment by selster** [comment]
I shoud not have said ctrl C and V, rather I should have said press copy in Duik Basel then paste!

**Comment by Nico-Duduf** [comment]
That's Ae. Check the spatial interpolation between the pasted keyframes.
