### ISSUE TITLE
"Extract" doesn't work in After Effects 2023

### ISSUE THREAD

**Issue by K-Da1e** [RxLaboratory/Duik#980]
**Description**

I can't "Extract" controllers in After Effects 2023. 

**To Reproduce**

1. Run AAE 2023
2. Start new project 
3. Create precomp 
4. In this precomp create any structure
5. Use "Auto-rig & IK"
6. Back to the main comp
7. Click "Extract"

**Additional context**

When i faced this bug, I reinstalled duik bassel but it didn't help 
"Tag" doesn't help to solve this problem neither
In AAE 2022 everything works fine

**System information**

[bug_extract.txt](https://github.com/RxLaboratory/Duik/files/10319047/bug_extract.txt)

**Comment by Nico-Duduf** [comment]
This should work in the new Duik 17 Ángela available soon.
In the meantime, try with expressions instead of essential properties, that may work
