### ISSUE TITLE
Strange deformation with unusual illustrated spines

### ISSUE THREAD

**Issue by andreastanner** [RxLaboratory/Duik#986]
Dear Nicolas

I'm not sure what's happening when I've got a spine that's not straight like most of the time but a more curvy one. When I autorig, the spine breaks and deforms the body weirdly. Is it technically not possible or a bug? My workaround is to create pins pins first and link them afterwards to the bones instead of directly make bones out of the pins created with the puppet pin. That way, it's not perfect but a bit better.

![Untitled-1](https://user-images.githubusercontent.com/55541491/214254059-9747943b-2b9a-4977-a86d-09091290fe16.jpg)

**Comment by Nico-Duduf** [comment]
Hi Andreas,

Yes there were a few issues with the spine rig in some versions but they should be fixed in the new version.

I'm keeping the issue opened here just so you can confirm it works with the new version when it's released ;)

thanks for the report!
