### ISSUE TITLE
Move anchor points with shape layers

### ISSUE THREAD

**Issue by siyexa2951** [RxLaboratory/Duik#991]
Duik 17.0.0 and 17.0.1 ae 2023

Move anchor points not correctly in Shape Layer with stroke.
<a href="https://imgbox.com/vXGIO26a" target="_blank"><img src="https://thumbs2.imgbox.com/17/a4/vXGIO26a_t.gif" alt="image host"/>

**Comment by Nico-Duduf** [comment]
Thanks for the report!
I'm splitting the issue,
Here's the one I'm creating about the IK: #992

**Comment by Nico-Duduf** [comment]
fixed in 17.0.2
