### ISSUE TITLE
experience of connector

### ISSUE THREAD

**Issue by Aimad-LQ** [RxLaboratory/Duik#994]
Hi,
  The experience of connector at Duik Angela is no better than Duik Bassel.
I have to go through multiple lists to do a specific action and I have to repeat it every time

I suggest that the last two steps be combined together

![duik](https://user-images.githubusercontent.com/48952173/215520799-9161f04f-88a4-4e9a-aaba-d3e9a08a736b.png)

**Comment by Nico-Duduf** [comment]
Done in 17.1.3
