### ISSUE TITLE
 alert message when pressing the auto-rig button

### ISSUE THREAD

**Issue by urekmazino00** [RxLaboratory/Duik#995]
is it possible to stop the alert message when pressing the auto-rig button?

**Comment by Nico-Duduf** [comment]
TODO:

- [ ] Add checkbox to the dialog to disable it
- [ ] Add option in Duik settings to re-enable it

**Comment by urekmazino00** [comment]
Ok, thanks

**Comment by Nico-Duduf** [comment]
done in 17.0.2
