### ISSUE TITLE
Bone rigging of the hair and FK.

### ISSUE THREAD

**Issue by siyexa2951** [RxLaboratory/Duik#999]
If the curve angle keyframe is not set to 0 at the beginning, the bones will not return even if it is set to 0 afterwards,
If the angle is set to 0 at the beginning, then the bones will return to their normal position even if the angle is set to 0 after.

<a href="https://imgbox.com/P99N9VvT" target="_blank"><img src="https://thumbs2.imgbox.com/94/71/P99N9VvT_t.gif" alt="image host"/></a>

**Comment by Nico-Duduf** [comment]
That's actually a "normal" behaviour, as the auto overlap amplifies the movement. The curve angle is not really meant to be animated but to pose the tail, and it's better to use the rotation of the controller for the animation (although you *can* use the curve value if you prefer, you just have to find the right value which won't be 0 for the straight pose)
